kind: Deployment
apiVersion: apps/v1
metadata:
  name: test-dply
spec:
  selector:
    matchLabels:
       app: test_pod
  template:
    metadata:
      labels:
        app: test_pod
    spec:
      containers:
      - name: mycontainer
        image: mmaksimovic1419s/dcr_server
        ports:
        - name: containerport
          containerPort: 8081