kind: Service
apiVersion: v1
metadata:
  name: prodigy-service
spec:
  type: LoadBalancer
  selector:
    app: test_pod
  ports:
    - name: sentiment
      protocol: TCP
      port: 8081
      targetPort: containerport